import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Sparkles, X, Search, Clock, Bookmark, Filter, Copy, Check, ExternalLink, RefreshCw, AlertCircle, FileText } from 'lucide-react';
import { Article, Feed, AppSettings } from '../types';
import { askLibraryAI, LibraryAnswer, LibraryQueryOptions } from '../services/librarySearchService';
import { downloadFile } from '../exportService';
import './AskLibrary.css';

interface AskLibraryProps {
    articles: Article[];
    feeds: Feed[];
    settings: AppSettings;
    onClose: () => void;
    onSelectArticle: (article: Article) => void;
}

const SUGGESTIONS = [
    "What are the biggest recent developments across my feeds?",
    "Summarize major AI & tech news from the past week",
    "What are the key takeaways from my saved articles?",
    "Synthesize market and economic news reported recently"
];

export default function AskLibrary({
    articles,
    feeds,
    settings,
    onClose,
    onSelectArticle
}: AskLibraryProps) {
    const [query, setQuery] = useState('');
    const [timeRange, setTimeRange] = useState<'all' | 'last24h' | 'last7d' | 'last30d'>('last7d');
    const [scope, setScope] = useState<'all' | 'saved' | 'unread'>('all');
    const [selectedCategory, setSelectedCategory] = useState<string>('all');
    const [isLoading, setIsLoading] = useState(false);
    const [answerData, setAnswerData] = useState<LibraryAnswer | null>(null);
    const [error, setError] = useState<string | null>(null);
    const [copied, setCopied] = useState(false);

    // Extract unique categories
    const categories = Array.from(
        new Set(feeds.map(f => f.category || 'Uncategorized'))
    ).filter(Boolean).sort();

    const handleSearch = async (searchQuery: string = query) => {
        const trimmed = searchQuery.trim();
        if (!trimmed) return;

        setIsLoading(true);
        setError(null);

        const options: LibraryQueryOptions = {
            timeRange,
            scope,
            category: selectedCategory !== 'all' ? selectedCategory : undefined
        };

        try {
            const result = await askLibraryAI(trimmed, articles, settings, options);
            setAnswerData(result);
        } catch (err: any) {
            console.error('AskLibrary error:', err);
            setError(err?.message || 'Failed to analyze library articles. Please verify your AI settings.');
        } finally {
            setIsLoading(false);
        }
    };

    const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
        if (e.key === 'Enter' && !e.shiftKey) {
            e.preventDefault();
            handleSearch();
        }
    };

    const handleCopy = async () => {
        if (!answerData) return;
        let text = `# ${answerData.query}\n\n${answerData.answer}\n\n## Sources\n`;
        answerData.retrievedArticles.forEach(item => {
            text += `[${item.index}] ${item.article.title} (${item.article.link})\n`;
        });

        await navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleExportMarkdown = () => {
        if (!answerData) return;
        const today = new Date().toISOString().split('T')[0];
        let md = `# Library AI Analysis: ${answerData.query}\n`;
        md += `*Generated by SimonReads on ${today} using ${answerData.provider}*\n\n`;
        md += `## Synthesis\n\n${answerData.answer}\n\n`;
        md += `## Cited Sources\n\n`;
        answerData.retrievedArticles.forEach(item => {
            const source = item.article.feedTitle || item.article.creator || 'RSS';
            md += `- **[${item.index}]** [${item.article.title}](${item.article.link}) — *${source}*\n`;
        });

        const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
        downloadFile(blob, `SimonReads_Analysis_${today}.md`, 'text/markdown');
    };

    return (
        <div className="ask-library-overlay" onClick={onClose}>
            <div className="ask-library-container" onClick={e => e.stopPropagation()}>
                {/* Header */}
                <div className="ask-library-header">
                    <div className="ask-library-title">
                        <Sparkles size={22} className="sparkles-icon" />
                        <div>
                            <h2>Ask My Library</h2>
                            <p className="subtitle">AI cross-source research & synthesis across your feeds</p>
                        </div>
                    </div>
                    <button className="ask-close-btn" onClick={onClose} aria-label="Close">
                        <X size={20} />
                    </button>
                </div>

                {/* Filters Bar */}
                <div className="ask-filters-bar">
                    <div className="filter-group">
                        <Clock size={14} />
                        <select
                            value={timeRange}
                            onChange={e => setTimeRange(e.target.value as any)}
                            disabled={isLoading}
                        >
                            <option value="last24h">Past 24 Hours</option>
                            <option value="last7d">Past 7 Days</option>
                            <option value="last30d">Past 30 Days</option>
                            <option value="all">All Time</option>
                        </select>
                    </div>

                    <div className="filter-group">
                        <Bookmark size={14} />
                        <select
                            value={scope}
                            onChange={e => setScope(e.target.value as any)}
                            disabled={isLoading}
                        >
                            <option value="all">All Articles</option>
                            <option value="saved">Saved Only ⭐</option>
                            <option value="unread">Unread Only</option>
                        </select>
                    </div>

                    {categories.length > 0 && (
                        <div className="filter-group">
                            <Filter size={14} />
                            <select
                                value={selectedCategory}
                                onChange={e => setSelectedCategory(e.target.value)}
                                disabled={isLoading}
                            >
                                <option value="all">All Categories</option>
                                {categories.map(cat => (
                                    <option key={cat} value={cat}>{cat}</option>
                                ))}
                            </select>
                        </div>
                    )}
                </div>

                {/* Input Search Box */}
                <div className="ask-input-wrapper">
                    <Search size={20} className="search-icon" />
                    <input
                        type="text"
                        value={query}
                        onChange={e => setQuery(e.target.value)}
                        onKeyDown={handleKeyDown}
                        placeholder="Ask anything across your feeds (e.g. 'What happened in AI this week?')"
                        autoFocus
                        disabled={isLoading}
                    />
                    <button
                        className="ask-submit-btn"
                        onClick={() => handleSearch()}
                        disabled={!query.trim() || isLoading}
                    >
                        {isLoading ? <RefreshCw size={18} className="spin-icon" /> : 'Ask AI'}
                    </button>
                </div>

                {/* Suggested Chips (when no answer or empty) */}
                {!answerData && !isLoading && (
                    <div className="ask-suggestions">
                        <span className="suggestions-label">Try asking:</span>
                        <div className="suggestion-chips">
                            {SUGGESTIONS.map((suggestion, idx) => (
                                <button
                                    key={idx}
                                    className="chip"
                                    onClick={() => {
                                        setQuery(suggestion);
                                        handleSearch(suggestion);
                                    }}
                                >
                                    {suggestion}
                                </button>
                            ))}
                        </div>
                    </div>
                )}

                {/* Loading State */}
                {isLoading && (
                    <div className="ask-loading-state">
                        <div className="pulse-spinner">
                            <Sparkles size={28} />
                        </div>
                        <h3>Scanning your library & synthesizing insights...</h3>
                        <p>Analyzing matching articles across your feeds</p>
                    </div>
                )}

                {/* Error Banner */}
                {error && !isLoading && (
                    <div className="ask-error-box">
                        <AlertCircle size={20} />
                        <div>
                            <strong>Analysis Failed</strong>
                            <p>{error}</p>
                        </div>
                    </div>
                )}

                {/* Answer View */}
                {answerData && !isLoading && (
                    <div className="ask-answer-scroll">
                        <div className="ask-answer-card">
                            <div className="answer-header">
                                <span className="provider-badge">Powered by {answerData.provider.toUpperCase()}</span>
                                <div className="answer-actions">
                                    <button className="action-btn" onClick={handleCopy} title="Copy to clipboard">
                                        {copied ? <Check size={16} /> : <Copy size={16} />}
                                        <span>{copied ? 'Copied!' : 'Copy'}</span>
                                    </button>
                                    <button className="action-btn" onClick={handleExportMarkdown} title="Export as Markdown">
                                        <FileText size={16} />
                                        <span>Export</span>
                                    </button>
                                </div>
                            </div>

                            <div className="answer-content markdown-body">
                                <ReactMarkdown remarkPlugins={[remarkGfm]}>
                                    {answerData.answer}
                                </ReactMarkdown>
                            </div>
                        </div>

                        {/* Cited Sources Section */}
                        {answerData.retrievedArticles.length > 0 && (
                            <div className="ask-sources-section">
                                <h3>📚 Sources from Your Library ({answerData.retrievedArticles.length})</h3>
                                <div className="sources-list">
                                    {answerData.retrievedArticles.map(item => (
                                        <div
                                            key={item.article.id}
                                            className="source-card"
                                            onClick={() => {
                                                onSelectArticle(item.article);
                                                onClose();
                                            }}
                                        >
                                            <div className="source-index-pill">[{item.index}]</div>
                                            <div className="source-info">
                                                <h4 className="source-title">{item.article.title}</h4>
                                                <div className="source-meta">
                                                    <span className="feed-name">{item.article.feedTitle || 'RSS Feed'}</span>
                                                    {item.article.pubDate && (
                                                        <span className="source-date">
                                                            • {new Date(item.article.pubDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
                                                        </span>
                                                    )}
                                                </div>
                                            </div>
                                            <ExternalLink size={16} className="open-icon" />
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}
                    </div>
                )}
            </div>
        </div>
    );
}
